### ISSUE TITLE
type script with serverless.yml

### ISSUE THREAD

**Issue by DeanZahavy** [completecoding/serverless-auto-swagger#103]
Thank you for your amazing work on this plugin, it makes life much easier :) 

i have an issue with importing the plugin on type script services. after installing and adding the plugin,

<img width="521" alt="image" src="https://user-images.githubusercontent.com/91829842/202461061-975c6a54-3bdb-422a-808a-ab8cd2ed9bcd.png">
<img width="443" alt="image" src="https://user-images.githubusercontent.com/91829842/202461137-3fdf0a99-505c-4f38-adc5-7da109908f5c.png">

when the service upload the tsconfig tries to access swager-html.ts while your plugin accept only JS files. 

<img width="766" alt="image" src="https://user-images.githubusercontent.com/91829842/202461739-78d70eab-9b19-4ba7-9db3-c611e33fa485.png">

to solver this for now i created a new plugin that copy you JS output into a TS file. but i am sure this is redundant, have any suggestion on how to create TS files using your plugin? 

my tsconfig file-
<img width="515" alt="image" src="https://user-images.githubusercontent.com/91829842/202461949-02dfbab7-16d3-4725-887a-95e70f2c344e.png">

agin thank you for the amazing work

**Comment by bfaulk96** [comment]
If serverless is looking for `swagger-html.ts`, it's something wrong with your tsconfig or serverless setup, not `serverless-auto-swagger`. I can confirm this plugin works fine with Typescript, as we use it in ~30 APIs at my current workplace. Unfortunately, I don't really know what would be causing that, nor do I have time to debug without a minimal reproducible example.
