### ISSUE TITLE
Can we disable 'Configuration warnings' ?

### ISSUE THREAD

**Issue by hukus** [completecoding/serverless-auto-swagger#37]
When building the API we see a lot of warnings about configuration. The list is getting a bit long and annoying. Is there any way to enable support for configuration validation for fields specific to auto-swagger?

```
Serverless: Configuration warning:
Serverless:   at 'functions.calculation.events[0].http.queryStringParameters.tags.type': should be equal to one of the allowed values [string, integer]
Serverless:   at 'functions.calculation.events[0].http.queryStringParameters.categories.type': should be equal to one of the allowed values [string, integer]Serverless:   at 'functions.calculation.events[1].http': unrecognized property 'bodyType'
Serverless:   at 'functions.calculation.events[4].http': unrecognized property 'bodyType'
Serverless:   at 'functions.calculation.events[5].http': unrecognized property 'bodyType'
Serverless:   at 'functions.calculation.events[6].http': unrecognized property 'bodyType'
Serverless:   at 'functions.calculation.events[7].http': unrecognized property 'bodyType'
Serverless:   at 'functions.calculation.events[8].http.queryStringParameters.ids.type': should be equal to one of the allowed values [string, integer]       
Serverless:   at 'functions.calculation.events[11].http': unrecognized property 'bodyType'
Serverless:   at 'functions.calculation.events[13].http.queryStringParameters.ids.required': should be boolean
Serverless:   at 'functions.calculation.events[13].http.queryStringParameters.ids.type': should be equal to one of the allowed values [string, integer]      
Serverless:   at 'functions.calculation.events[15]': unsupported function event
Serverless:   at 'functions.calculation.events[16].http.queryStringParameters.ids.required': should be boolean
Serverless:   at 'functions.calculation.events[16].http.queryStringParameters.ids.type': should be equal to one of the allowed values [string, integer] 
```

**Comment by bfaulk96** [comment]
Any chance you could share some of your `queryStringParameters` causing this?
I'm working on fixing these validations now.

`bodyType` and `description` were straight up missing, so I'm working on those, but to make sure I cover the queryStringParameters correctly, any additional info would be helpful

**Comment by bfaulk96** [comment]
I've made a PR to address these warnings.

**Comment by bfaulk96** [comment]
@hukus Sorry about the delay. All validations should be accurate to the docs as of `2.4.0`

**Comment by jguerinet** [comment]
Hi @bfaulk96 , would it be possible to update the validation for `httpApi` as well? When using `http` no warnings appear, but the second you use `httpApi` it seems like none of the autoswagger properties are recognized:
```
Warning: Invalid configuration encountered
  at 'functions.newProgram.events.0.httpApi': unrecognized property 'swaggerTags'
  at 'functions.updateProgram.events.0.httpApi': unrecognized property 'responses'
```

**Comment by bfaulk96** [comment]
Will look into this tomorrow!

**Comment by bfaulk96** [comment]
This has been fixed in [v2.8.1](https://github.com/completecoding/serverless-auto-swagger/releases/tag/v2.8.1) 😄

**Comment by jguerinet** [comment]
Thanks @bfaulk96, looks like it's _almost_ good to go. Seems like your schema is missing the following properties: 
* `summary` property on the events
* `title` property in the autoswagger config (which was added in v2.8.0). 
If it's as simple as just editing the schema json files to add those properties, happy to do it and open a PR if that's easier.

**Comment by bfaulk96** [comment]
@jguerinet Whoops, yes, it is that simple. I don't mind making the change though, as I evidently missed those when approving PRs previously

**Comment by bfaulk96** [comment]
2.8.2 has been published 😄

**Comment by jguerinet** [comment]
Works perfectly now, thanks @bfaulk96 !
