### ISSUE TITLE
typescript union type definitions not reflecting properly in swagger models

### ISSUE THREAD

**Issue by newtechfellas** [completecoding/serverless-auto-swagger#83]
Given below type definitions in typescript:
`export type HospitalCategory = "Allopathy" | "Homeopathy" | "Ayurveda" | "Naturopathy" | "Other";

export interface Hospital {
  name: string;
  email: string;
  phoneNumber: string;
  category: HospitalCategory;
  ...
  ...
}`
On generating swagger documentation, UI reflects incorrect type for category field. Is this expected?
<img width="303" alt="Screen Shot 2022-07-25 at 9 40 59 PM" src="https://user-images.githubusercontent.com/6200948/180911590-fa75c9ec-17ca-47a6-bfd3-45c1680812c6.png">

**Comment by bfaulk96** [comment]
This is not the type, this is an "Example Value".

If you click on `Model`, it correctly shows the various options. This description is simply a view of a "possible response", which "Allopathy" is.
