### ISSUE TITLE
Add custom operationId configuration

### ISSUE THREAD

**Issue by amm1992** [completecoding/serverless-auto-swagger#84]
When auto generating a function with the following example path
path: 'products/get-product/{catalogueRef}'

It generates the following in swagger
"operationId": "products.get.product/get-products/{categoryId}/",

On our frontend application we use a package to generate the connection to our api and it auto creates the function names from the operation ID. This causes overly complicated function names like "productsGetProductGetProductsCategoryId"

It would be useful if there was an option to manually define the operationId (unless there already is and I can't see anything) as this would allow us to define more meaningful names

**Comment by bfaulk96** [comment]
Just a reminder that this tool is used to automatically create a Swagger document from your Serverless file, but not necessarily meant to be a "catch-all" for every case and purpose. The swagger.json generated can theoretically be updated _after_ this plugin generates it originally.

That being said, this is probably doable, and we always welcome contributions 😄

**Comment by trbarton** [comment]
I've just had the exact same scenario. I've submitted a PR #100 for it

**Comment by trbarton** [comment]
@bfaulk96 I think this can be closed now. PR #100 is now merged
