### ISSUE TITLE
Add authorizer to generated swagger endpoints

### ISSUE THREAD

**Issue by tahjgayfield** [completecoding/serverless-auto-swagger#86]
Is there a way to add an authorizer to the `/swagger` endpoint that is generated by this plugin?

**Comment by chelodegli** [comment]
If you mean the "Authorize" button on top, you could set it up like this in your serverless.yml:

```
custom:
    autoswagger:
        apiKeyHeaders: ['authentication-token']
```

**Comment by bfaulk96** [comment]
@tahjgayfield this feature has been added as of release `v2.9.2` 😄 

You can add a custom authorizer for `/swagger` and `/swagger.json` with the custom config option

```yaml
lambdaAuthorizer: ${self:custom.customAuthorizer}
```
