### ISSUE TITLE
Since I need to have my swagger documentation on UAT/Dev Environment, is there a way to protect the swagger endpoints behind some Authorisation method (token, user/pass)?

### ISSUE THREAD

**Issue by tihobanov** [completecoding/serverless-auto-swagger#93]
Since I need to have my swagger documentation on UAT/Dev Environment, is there a way to protect the swagger endpoints behind some Authorisation method (token, user/pass)?

_Originally posted by @tihobanov in https://github.com/completecoding/serverless-auto-swagger/discussions/91_

**Comment by bfaulk96** [comment]
Closing as duplicate of https://github.com/completecoding/serverless-auto-swagger/issues/86. Will be looking into it!
